--
-- -- truncate TABLE member;
-- -- truncate TABLE member_role;
-- -- truncate TABLE member_roles;
--
-- insert into member (memberid,member_phone, member_name,member_pwd,member_score) values (1,'18028222222', 'wdf2','wdf2',123);
-- insert into member (memberid,member_phone, member_name,member_pwd,member_score) values (2,'18028222223', 'wdf3','wdf3',123);
-- insert into member (memberid,member_phone, member_name,member_pwd,member_score) values (3,'18028222224', 'wdf4','wdf4',123);
-- insert into member (memberid,member_phone, member_name,member_pwd,member_score) values (4,'18028222225', 'wdf5','wdf5',123);
-- insert into member (memberid,member_phone, member_name,member_pwd,member_score) values (5,'18028222226', 'wdf6','wdf6',123);
-- insert into member_role(id,name) values(1,'ROLE_ADMIN');
-- insert into member_role(id,name) values(2,'ROLE_USER');
--
-- insert into member_roles(member_memberid,roles_id) values(1,1);
-- insert into member_roles(member_memberid,roles_id) values(2,2);
-- insert into member_roles(member_memberid,roles_id) values(3,2);
-- insert into member_roles(member_memberid,roles_id) values(4,2);
-- insert into member_roles(member_memberid,roles_id) values(5,2);
--
-- -- insert into score (scoreRecordID,memberid, growthScore,time,remark) values (1,1,1,null,null);
--
